name = "RoughSurfaces"
uuid = "381b59a5-910b-47a1-8113-34fc61befd2a"
authors = ["Robert Lee Gates <rleegates@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
